//! Language Profile comparison example
//!
//! This example compares names generated by different language profiles
//! and demonstrates the various features of the language profile system.

use name_generator::core::Name;
use name_generator::categories::profile_examples::*;
use name_generator::language_profile::profile::LanguageProfile;
use name_generator::generators::profile_generator::LanguageProfileGenerator;
use rand::{SeedableRng};
use rand_chacha::ChaCha8Rng;

fn main() {
    // Use seeded RNG for reproducible results
    let mut rng = ChaCha8Rng::seed_from_u64(42);
    
    println!("=== Language Profile Comparison ===\n");
    
    println!("1. German Language Profile:");
    let german_gen = Name::<GermanLanguageProfile>::new();
    for i in 0..5 {
        let name = german_gen.generate(&mut rng);
        println!("     {}: {}", i + 1, name);
    }
    
    println!("\n2. English Language Profile:");
    let english_gen = Name::<EnglishLanguageProfile>::new();
    for i in 0..5 {
        let name = english_gen.generate(&mut rng);
        println!("     {}: {}", i + 1, name);
    }
    
    println!("\n3. Direct Profile Generator Usage:");
    let test_profile = LanguageProfile::create_simple_test_profile();
    let direct_gen = LanguageProfileGenerator::new(&test_profile);
    println!("   Direct test profile names:");
    for i in 0..5 {
        let name = direct_gen.generate(&mut rng);
        println!("     {}: {}", i + 1, name);
    }
    
    println!("\n4. Language Profile Characteristics Analysis:");
    
    // Reset RNG for consistent analysis
    let mut rng = ChaCha8Rng::seed_from_u64(42);
    
    println!("\n   German Profile characteristics:");
    let german_names: Vec<String> = (0..20)
        .map(|_| german_gen.generate(&mut rng))
        .collect();
    analyze_names("German Profile", &german_names);
    
    // Reset RNG again
    let mut rng = ChaCha8Rng::seed_from_u64(42);
    
    println!("\n   English Profile characteristics:");
    let english_names: Vec<String> = (0..20)
        .map(|_| english_gen.generate(&mut rng))
        .collect();
    analyze_names("English Profile", &english_names);
    
    println!("\n5. Feature Comparison:");
    println!("   Language profiles provide:");
    println!("     - Phonetic accuracy based on IPA");
    println!("     - Syllable structure rules");
    println!("     - Morphological composition");
    println!("     - Harmony rules and frequency adjustments");
    println!("     - Forbidden sound transitions");
    
    println!("\n=== Comparison Complete ===");
}

fn analyze_names(system_name: &str, names: &[String]) {
    let avg_length: f32 = names.iter().map(|n| n.len()).sum::<usize>() as f32 / names.len() as f32;
    let min_length = names.iter().map(|n| n.len()).min().unwrap_or(0);
    let max_length = names.iter().map(|n| n.len()).max().unwrap_or(0);
    
    println!("     {}: avg={:.1}, min={}, max={}", 
             system_name, avg_length, min_length, max_length);
    
    // Show a few examples
    print!("     Examples: ");
    for (i, name) in names.iter().take(3).enumerate() {
        if i > 0 { print!(", "); }
        print!("{}", name);
    }
    println!();
}